name: Deploy to VPS

on:
  push:
    branches:
      - main  # Thay thành master nếu nhánh mặc định của bạn là master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Triển khai mã nguồn qua SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/he-thong-vay
            git pull origin main
            npm install
            pm2 restart vay-online
